export default defineAppConfig({
    shadcnDocs: {
        site: {
            name: 'doc-akora',
            description: 'Library of informations about games on all platforms from RAWG, and lot of news from IGN.',
            ogImage: '/hero.png',
            ogImageComponent: 'ShadcnDocs',
            ogImageColor: 'light',
        },
        theme: {
            customizable: true,
            color: 'yellow',
            radius: 1,
        },
        banner: {
            enable: false,
            showClose: true,
            content: 'Welcome to **akora**',
            to: 'https://github.com/alexis-gss/akora',
            target: '_blank',
            border: true,
        },
        header: {
            title: 'doc-akora',
            showTitle: true,
            logo: {
                light: '/logo.svg',
                dark: '/logo-dark.svg',
            },
            darkModeToggle: true,
            nav: [{
                title: 'Docs',
                links: [{
                    title: 'Getting Started',
                    to: '/getting-started/introduction',
                    description: 'Start building your document with shadcn-docs-nuxt',
                    icon: 'lucide:rocket',
                }, {
                    title: 'Project',
                    to: '/project/first-part',
                    description: 'Explore available UI components and usage examples.',
                    icon: 'lucide:folder',
                }, {
                    title: 'About',
                    to: '/about/project-management',
                    description: 'Discover the configurations and exposed APIs.',
                    target: '_self',
                    icon: 'lucide:info',
                }],
            }, {
                title: 'Links',
                links: [{
                    title: 'Portfolio',
                    to: 'https://alexis-gousseau.com',
                    description: 'Discover my portfolio with the main projects I\'ve completed.',
                    target: '_blank',
                }, {
                    title: 'Github profile',
                    to: 'https://github.com/alexis-gss',
                    description: 'Explore my public repositories from my Github profile and more.',
                    target: '_blank',
                }],
            }],
        },
        aside: {
            useLevel: true,
            collapse: false,
            collapseLevel: 1,
            folderStyle: 'default',
        },
        main: {
            breadCrumb: true,
            showTitle: true,
            codeCopyToast: true,
            codeCopyIcon: 'lucide:copy',
            editLink: {
                enable: true,
                pattern: 'https://github.com/alexis-gss/documentations/edit/master/content/:path',
                text: 'Edit this page',
                icon: 'lucide:square-pen',
                placement: ['docsFooter', 'toc'],
            },
            backToTop: true,
            codeIcon: {
                'package.json': 'vscode-icons:file-type-node',
                'tsconfig.json': 'vscode-icons:file-type-tsconfig',
                '.npmrc': 'vscode-icons:file-type-npm',
                '.editorconfig': 'vscode-icons:file-type-editorconfig',
                '.eslintrc': 'vscode-icons:file-type-eslint',
                '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
                '.eslintignore': 'vscode-icons:file-type-eslint',
                'eslint.config.js': 'vscode-icons:file-type-eslint',
                'eslint.config.mjs': 'vscode-icons:file-type-eslint',
                'eslint.config.cjs': 'vscode-icons:file-type-eslint',
                '.gitignore': 'vscode-icons:file-type-git',
                'yarn.lock': 'vscode-icons:file-type-yarn',
                '.env': 'vscode-icons:file-type-dotenv',
                '.env.example': 'vscode-icons:file-type-dotenv',
                '.vscode/settings.json': 'vscode-icons:file-type-vscode',
                'nuxt': 'vscode-icons:file-type-nuxt',
                '.nuxtrc': 'vscode-icons:file-type-nuxt',
                '.nuxtignore': 'vscode-icons:file-type-nuxt',
                'nuxt.config.js': 'vscode-icons:file-type-nuxt',
                'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
                'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
                'tailwind.config.js': 'vscode-icons:file-type-tailwind',
                'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
                'vue': 'vscode-icons:file-type-vue',
                'ts': 'vscode-icons:file-type-typescript',
                'tsx': 'vscode-icons:file-type-typescript',
                'mjs': 'vscode-icons:file-type-js',
                'cjs': 'vscode-icons:file-type-js',
                'js': 'vscode-icons:file-type-js',
                'jsx': 'vscode-icons:file-type-js',
                'md': 'vscode-icons:file-type-markdown',
                'mdc': 'vscode-icons:file-type-markdown',
                'css': 'vscode-icons:file-type-css',
                'py': 'vscode-icons:file-type-python',
                'npm': 'vscode-icons:file-type-npm',
                'pnpm': 'vscode-icons:file-type-pnpm',
                'npx': 'vscode-icons:file-type-npm',
                'yarn': 'vscode-icons:file-type-yarn',
                'bun': 'vscode-icons:file-type-bun',
                'yml': 'vscode-icons:file-type-yaml',
                'json': 'vscode-icons:file-type-json',
                'terminal': 'lucide:terminal',
            },
        },
        footer: {
            credits: 'Copyright © ' + new Date().getFullYear(),
            links: [{
                icon: 'lucide:globe',
                to: 'https://alexis-gousseau.com',
                target: '_blank',
            }, {
                icon: 'lucide:github',
                to: 'https://github.com/alexis-gss/documentations',
                target: '_blank',
            }],
        },
        toc: {
            enable: true,
            enableInMobile: false,
            enableInHomepage: false,
            title: 'On This Page',
            links: [{
                title: 'Star on GitHub',
                icon: 'lucide:star',
                to: 'https://github.com/alexis-gss/documentations',
                target: '_blank',
                showLinkIcon: true,
            }, {
                title: 'Create Issues',
                icon: 'lucide:circle-dot',
                to: 'https://github.com/alexis-gss/documentations/issues',
                target: '_blank',
                showLinkIcon: true,
            }],
        },
        search: {
            enable: true,
            inAside: false,
        },
    },
    theme: {
      customizable: true,
      color: 'zinc',
      radius: 0.5,
    },
    header: {
      title: 'shadcn-docs-starter',
      showTitle: true,
      darkModeToggle: true,
      languageSwitcher: {
        enable: false,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      nav: [],
      links: [{
        icon: 'lucide:github',
        to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
        target: '_blank',
      }],
    },
    aside: {
      useLevel: true,
      collapse: false,
    },
    main: {
      breadCrumb: true,
      showTitle: true,
    },
    footer: {
      credits: 'Copyright © 2024',
      links: [{
        icon: 'lucide:github',
        to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
        target: '_blank',
      }],
    },
    toc: {
      enable: true,
      links: [{
        title: 'Star on GitHub',
        icon: 'lucide:star',
        to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
        target: '_blank',
      }, {
        title: 'Create Issues',
        icon: 'lucide:circle-dot',
        to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt/issues',
        target: '_blank',
      }],
    },
    search: {
      enable: true,
      inAside: false,
    }
});
